### ISSUE TITLE
[FEATURE]: Urban buses in the Principality of Andorra

### ISSUE THREAD

**Issue by janfajessen** [vingerha/gtfs2#33] opened 2024-03-02 05:03 UTC
I have searched for the gtsf from Andorra and on their website 
https://www.fedasolucions.ad/appintern
they provide a Zip gtsf file and a real time file that I don't know what ending it has.  
I have tried installing the Zip file in the gtfs2 folder and it does not work in the UI with the name without .zip, I do not know if they really provide me with the correct files for this integration. 
I also don't know if it is possible to add in the next update.  

You have done a great job and it would be very useful to me, it is a shame that it does not work for me

**Comment by vingerha** [comment] 2024-03-02 05:41
Hey, you can just use the URL... https://www.fedasolucions.ad/appintern/gtfs_coopalsa/at_download/file
It installs fine...but, I just VERY quickly checked it and it cannot find routes today for the first one in the list...maybe this is because there are no buses today? I am travelling so no further time to analyse

**Comment by janfajessen** [comment] 2024-03-02 06:42
Yes, thank you, it works!
But it is strange because there are buses now that can be seen in that app,
it seems that what can see now are from the night line and are not updated.
I don't know if the real time file influences that update but I don't know
how it would be added.
Don't worry, when you can there is no rush, enjoy the trip

**Comment by vingerha** [comment] 2024-03-02 12:22
I checked the data and this is old stuff, if you look in the zip and open 'calendar_dates' then you see all is from 2023 so the app will not show anything as it filters on dates too.
Not sure if there are other sources you can use...you'd have to search a bit or ask th eprovider? I am closing this as the issue is not with the app :)

**Closed by vingerha** 2024-03-02 12:22 UTC

**Comment by janfajessen** [comment] 2024-03-02 15:07
Ok, no worries, I will check to the provider or maybe a possibility to
modify manually. Thanks

**Comment by vingerha** [comment] 2024-03-02 15:27
If the schedules are the same then you can probably just change the 2023 into 2024 but I would first go for the provider as tinkering with data may lead to errors in the output
